### ISSUE TITLE
Current binaries?

### ISSUE THREAD

**Issue by bjoernross** [valentjn/santa-racer-rust#1]
Hi, I found your project by chance while trying to get Nikolaus Express 2000 to run properly on Windows 10 (the .scr file starts once you manage to get it out of the .exe but it's very slow and choppy). Funny that my family and I are not the only ones who thought of the old screensaver as Christmas approaches!

I tried running it from the v1.0.0 Windows binary. I have the assets in an assets folder inside the game folder and started the game, but most of the it does not seem to be working properly. I can see the sleigh and landscape, but no buildings, chimneys, or items. I saw that one of your last commits changed something about the level assets, wheras the binary I have been running is the one from the release two weeks ago, so I was wondering if that would already fix it - and in case it does, if you had plans to upload a new binary?

(I also tried running the Linux binary but it seems to be missing some libraries? I did extract the assets on Linux, because of the dependencies like wrestool. That seems to have worked fine except for the .ogg file - the version of timidity I was using was too old to have the --segment option. The level.png file is there.)

**Comment by valentjn** [comment]
Wow, I didn't expect anyone to recall that this game even existed. Sweet 2000, when people spent money for screensavers and ringtones ;)

I'm only using the game as an excuse to learn Rust, like I did in 2010 with [C++](https://github.com/valentjn/santa-racer-cpp). I'm not really playing the game, so there might be a lot of bugs in there.

Your problem was that you used the binaries from the 1.0.0 release, but the extraction script from `develop`, when you should have used the script from the [`1.0.0` tag](https://github.com/valentjn/santa-racer-rust/tree/1.0.0). I've pushed a [1.0.1 release](https://github.com/valentjn/santa-racer-rust/releases/tag/1.0.1) now, which should also fix your problem (if you use the script from the [new tag](https://github.com/valentjn/santa-racer-rust/tree/1.0.1)).

All `--segment` does is cutting off the final two minutes or so of silence, you can do that by hand. Shipping dependencies of Linux binaries is still a mystery to me, but if you have a Linux machine, it should be pretty easy to just [compile it yourself](https://github.com/valentjn/santa-racer-rust/blob/1.0.1/README.md#building-the-game). All it takes is installing a few packages, running the script from `sh.rustup.rs`, and finally `cargo run`.

**Comment by bjoernross** [comment]
Thanks, that makes a lot of sense! I can play the game now. A blast from the past!

If this is just a practice project, would you still like me to report any bugs I find?

**Comment by valentjn** [comment]
Sure, open issues if you want to. It's just that I can't guarantee I'll have the time to fix them.
