### ISSUE TITLE
Highscores only show after winning

### ISSUE THREAD

**Issue by bjoernross** [valentjn/santa-racer-rust#2]
At the moment the player has to win the game to be able to enter their name and have their highscore recorded (because `score_points` in `ui.rs` is only set if the player wins).

In the original game you could lose and still have your score counted. Pressing the escape key also triggered the "Nikolaus zu langsam" splash followed by the highscore screen.

Is this a bug or a design decision? :-)

**Comment by valentjn** [comment]
Not a conscious design decision, but I'm not convinced that it makes sense to deserve a high score if you lose. Granted, high scores come from arcade games where losing (eventually) was the only outcome, but if there's the option of winning, being able to get a high score sounds like a good reward to me (apart from getting the point bonus).

The escape key doesn't trigger a splash screen because you should be able to quickly exit the game (also useful while developing the game). That's another reason for not having a high score when pressing escape.
